### ISSUE TITLE
MWh à passer en %

### ISSUE THREAD

**Issue by martinregner** [datagir/vertvolt#11]
Selon la complexité, les premiers retours fournisseurs montrent qu'il est plus clair d'afficher des % sur les tableaux à côté des cartes : 

## Origine de l'elec 
![image](https://user-images.githubusercontent.com/46482115/137356123-d29df37b-3868-4cc6-8424-0a8a602a86ea.png)

### Par région : 
- au niveau de la région, le pourcentage par rapport au national
- la somme au niveau de chaque filière à l'intérieur d'une région fait 100% 
![image](https://user-images.githubusercontent.com/46482115/137356339-2c964934-532d-4f61-aa37-cd00656d9b66.png)

## Idem au sein de l'additionnalité :
- Part de l'électricité achetée à des installations construites après 2015 sans soutien public
- Part de l'électricité achetée à des installations en gouvernance partagée

**Comment by martinregner** [comment]
Ca marche 👍 
Il faudrait juste : 
- Multiplier par 100
- Arrondir en ne gardant qu'un chiffre après la virgule

![image](https://user-images.githubusercontent.com/46482115/137483556-c7a093e2-7307-409c-9389-c4feff8ac85e.png)

**Comment by florianpanchout** [comment]
C'est fait ! Par contre l'arrondi fait que l'on arrive toujours pas à 100 en additionnant toutes les sources

**Comment by florianpanchout** [comment]
Modification faite
