### ISSUE TITLE
Erreur carte EDF : apparaît tout en bleu sur la page du label

### ISSUE THREAD

**Issue by martinregner** [datagir/vertvolt#17]
Il semble y avoir une erreur sur la carte concernant l’offre d’EDF, elle apparaît tout en bleu sur la [page du label](https://agirpourlatransition.ademe.fr/particuliers/vertvolt) : 
![image](https://user-images.githubusercontent.com/46482115/144273768-208a3ccc-99ba-44b9-aeed-593b1d595ac1.png)

Pourtant dans les données, il semble pourtant contenir les bonnes informations (plusieurs technos / régions)

**Comment by florianpanchout** [comment]
Corrigé

**Comment by martinregner** [comment]
Top ! merci
