### ISSUE TITLE
Bug mise à jour data

### ISSUE THREAD

**Issue by martinregner** [datagir/vertvolt#18]
De nouvelles offres GEG sont arrivées dans le JDD mais ne s'affichent pas.

Vue métier :

> il semble y avoir un problème, une seule offre apparaît et les données ne sont pas les bonnes. Le problème pourrait venir du fait que les offres aient le même nom, mais que le nom du fournisseur change. Cela provient d’une spécificité du fournisseur, qui est une entreprise locale de distribution. Plus simplement, il commercialise la même offre (Yeli Circuit Court) mais avec le nom GEG sur une partie du territoire, et le nom GEG Sources d’énergies sur le reste du territoire. 

Réponse de Koumoul : 
> Coté données brutes, je vois bien 2 offres (ils y a 104 lignes de données / offre) pour "Yeli circuit court" et 2 distributeurs : "GEG" et "GEG source d'energies"
https://data.ademe.fr/datasets/vertvolt/full?nom_offre_in=%22Y%C3%A9li%20circuit%20court%22

> Je pense avoir trouvé le problème : https://github.com/datagir/vertvolt/blob/64313bf925b3a151beb4314e3a15091c617683a6/src/direflow-components/vertvolt-component/utils/api.js#L10
Il faut sans doute faire une double agrégation sur nom_offre et nom_fournisseur : https://data.ademe.fr/data-fair/api/v1/datasets/vertvolt/values_agg?field=nom_offre;nom_fournisseur&size=1&select=nom_offre,niveau_labelisation,statut_offre,nom_fournisseur,Recours_ARENH_fournisseur,clients_offre_labelisee

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
Merci !!
